name: ci

on: [push]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Security Audit
        run: npm audit --audit-level=critical

      - name: Install dependencies
        run: npm install

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      # - name: Tests
      #   run: npm run test

      - name: Ensure that no files changed
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "ERROR: uncommited changes in the repository"
            git status --porcelain
            exit 1
          fi
